language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: f/yyLrNDFyMNuGe8Nocz97hSa9zX3uh15fkJE7Ojy7a1HeGgKDwTwocjvkJPu/sruzTAq5VQnXAm7gpFcLa0cysXlRAqQifwXERp8WdhFKKVweZ4MiOUjlRfHYTiS1UFJMI9J52fEGLRNABCDCSUWTnufLI0XfXu4TSEhFWGJ2FcBuJNkFG19IW6l4DA01QWMv9SO50u3+pzFWI/1pM1XFhXv0S9D91XcWAngVOvijr9vwc0PdacndjjZizCg1dQRjj8zuf5vhTYML8X14Yo2qOvjLz9g1RLidA1EclgI0OlkzIC7XHTBlOAEU5njEYa/plULl//ogFz52g0IgglWx0AOci9qVW4bkNeYuVAYc1Z9KxTkR5I9+BncTUy8KN6yanZ2XmqeMHgqYLZXyYYq+hLr3YdU1rf2f1mFSlvZRlZ6A/ryDu0oL20weX+xVj+TytctnTOHRgb8/8Dxgl5VtZLdHiaVVo77ACR49DfAUjHcYdksASzC6/Ud9FnbBRo66NxAKMgR2HJRLTBSA2WslEf7qiPxPtHg20X+/yl8ohWsj2fWzd9XZgpSmQZkYYzPcz1TZOkdsDR6NtHTGEPH7iR4nADUr7PbeefupDJYzXzRuZHMxn1Cj4v3XVW69WvLDTqtwF+9yvdsFUj71thtAgEQlkDktl+TIao1HeuHcg=
  app: pacific-refuge-46518
  on:
    repo: Yitzi2/blog-challenge
'':
  travis:
    yml:
      secure: XvmlEaN4VO7vyOGAQLvbGWETpU8vTclcfulrN2NaAe5I4N26sLvnc97hhFCh8cJHecY3ssYSWzKSmmBl3fBUlnMBjMH2VX9H7Xpfne+6CCV/lkT8EgTEz7cfrUzdQnYcpgp9w5CO50NXYm337H+pm05xH22+CChf6R6V/iMKxX9TIdia/e4ieSSKU7KALBFlRX8d0x+yBdz7QYOLCU3qB3eNC7LIPv3SY13osvVvPo5sy6hJbE2bN/CZNpaXWuvm6r3VepexvTQqwTljMrtk7jdSDObvDdapEkvkolFN9Xi9gxTGzBfxCqhPjLJVpGI1RgKQZH+i9XvsLUs+HSzQZ9UmBDjYvjhNJJZmB/8zcre85B8iLTPMqXTuQvnJsKEzsh95qYIFJIRYNxT3xY8PImsCIQ5LWqeI5ITOPkDMjBiHqXsxeiDYgj3LwrfJT01tAC1MA+b5lhVK762OkYnCv8pBp6nddifzkuXu4re1i3kDtgGUQ22y458RaFTL9FpVMPXUaeB02cK5KaTSSnq+855O3QIui/Z8ZvnXr4QqR0xOEaYpgzMMppuaS8nTIaWyRKVXdy7ziz5JOg9H2Sdg7yNEu4odhtB+B4TKNjR7ufGJqqdTuFM+d6/dFgLtlWAGNHA9fUtwRLMdWygGKgPGIPifhZz5ea3Re/1zZDLV0gk=
